[project]
name = "mcp-server-fetch"
version = "0.1.0"
description = "A Model Context Protocol server that provides web content fetching capabilities"
requires-python = ">=3.8"
dependencies = [
    "mcp-server-fetch",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 